### ISSUE TITLE
Calling without haplotagged alignments

### ISSUE THREAD

**Issue by kcleal** [KolmogorovLab/Severus#12]
Hi @fenderglass,
Thanks for the great tool. For tumour only or germline calling with a single sample, does using non haplotagged alignments effect performance or runtime?
Thanks!

**Comment by fenderglass** [comment]
@aysegokce would know!

**Comment by aysegokce** [comment]
Hello @kcleal,
It only affects borderline cases with low VAF for SV detection but can affect SV clustering depending on the complexity of the genome. 

In terms of run time, it is actually slightly shorter with unphased bams. 
Ayse

**Comment by kcleal** [comment]
Thanks @aysegokce
