### ISSUE TITLE
How to understand the haplotags in the output file

### ISSUE THREAD

**Issue by ywzhang071394** [KolmogorovLab/Severus#29]
Hi,

Thank you for the nice tool. We recently used severus to detect the somatic variants from Pacbio data. However, we are confused of the haplotags in the output file.
For example:
Below is a large deletion of chr8: 43010350-67270902. The reads supporting this deletion are very far apart and are definitely not in the same phase set. In this case, their haplotags were not comparable. But how can severus report it as HP=1? Also, for inter-chromosome translocations, they must be in different phase sets. How can we understand the meaning of HP tags?
 
`chr8	43010350	severus_DEL6851	N	<DEL>	60.0	PASS	PRECISE;SVTYPE=DEL;SVLEN=24260552;END=67270902;STRANDS=+-;MAPQ=60.0;PHASESETID=42840731|67041081;HP=1	GT:GQ:VAF:hVAF:DR:DV	0/1:153:0.26:0.00,0.43,0.00:17:6`

Thank you so much!

**Comment by aysegokce** [comment]
Hello @ywzhang071394,
Thank you for bringing this to our attention. We are reporting only the first breakpoint's haplotype to prevent any confusion with the hVAF field. We will incorporate the HP tag for the second breakpoint in the upcoming releases. 

Thank you
Ayse

**Comment by ywzhang071394** [comment]
Thank you Ayse!
