### ISSUE TITLE
Question: distinction between DEL and DEL-like BND events

### ISSUE THREAD

**Issue by ajw2329** [KolmogorovLab/Severus#30]
Hello -- thanks for writing this fantastic tool!  

In looking into severus output and comparing to other callers, I've identified some examples where severus seems to be representing deletions by their constituent breakends.  This got me wondering whether their is a distinction between DEL-like breakends and events classed explicitly by severus as DELs.  

In this example event below, severus (working off of PacBio HiFi reads) calls the event a pair of BNDs, whereas Manta, working off of Illumina short read data generated from the same sample, calls the event a DEL.  Minda successfully identifies the severus and manta events as one and the same.  Because it's clear that severus often _does_ explicitly categorize events as DELs, I was confused as to why it didn't in this case.  Could you help me understand?  Apologies if I'm missing the explanation somewhere!

**Severus representation**
chr14	21724318	severus_BND2141_1	N	]chr14:22522039]N	60.0	PASS	PRECISE;SVTYPE=BND;SVLEN=797721;MATE_ID=severus_BND2141_2;STRANDS=+-;MAPQ=60.0;PHASESETID=21703814|22377673;HP=2	GT:GQ:VAF:hVAF:DR:DV	0/1:193:0.64:0.00,0.00,0.85:13:23
chr14	22522039	severus_BND2141_2	N	N[chr14:21724318[	60.0	PASS	PRECISE;SVTYPE=BND;SVLEN=797721;MATE_ID=severus_BND2141_1;STRANDS=+-;MAPQ=60.0;PHASESETID=21703814|22377673;HP=2	GT:GQ:VAF:hVAF:DR:DV	0/1:193:0.64:0.00,0.00,0.85:13:23

**Manta representation**
chr14	21724318	MantaDEL:99758:0:1:0:0:0	G	\<DEL\>    .   PASS	END=22522039;SVTYPE=DEL;SVLEN=-797721;SVINSLEN=10;SVINSSEQ=GGGGGTCTTC;SOMATIC;SOMATICSCORE=128	PR:SR	34,0:54,0	5,12:25,16

**Comment by aysegokce** [comment]
Hello!

We separate 'true deletions, ' which decrease coverage, from those that are DEL-like but do not actually change coverage. 

If there are multiple overlapping events altering the CN state in the region(clonal or subclonal), Severus outputs it as a BND to be safe. 

Thank you!
Ayse

**Comment by ajw2329** [comment]
Thanks very much!
