### ISSUE TITLE
explanation of TIN-ratio?

### ISSUE THREAD

**Issue by apsteinberg** [KolmogorovLab/Severus#33]
Hello,

Thank you for building this great tool. I am doing somatic SV calling, and I wanted to filter out any SVs which have a single supporting read in the normal tissue. Is this possible with the TIN-ratio parameter? Could I set this to `--TIN-ratio 0`?

I was also wondering if you could elaborate on what this parameter is?

Thanks for your time and help.

Best,
Asher

**Comment by aysegokce** [comment]
Hello,
We added this parameter as a request from our clinic collaborators. This parameter is helpful if there is a risk for tumor contamination in the normal samples, i.e., circulating tumor cells in the blood, adjacent normal, or leukemias. 
If there is no suspicion, you can set it to 0 to filter anything that appears normal. 

Best
Ayse

**Comment by apsteinberg** [comment]
Hi Ayse,

Thank you for explaining and the quick reply! Admittedly I am still confused as to what the TIN-ratio is though. Is this the ratio of reads supporting the SV to those which do not which appears in the normal? Thanks again for your time and help.

Best,
Asher

**Comment by aysegokce** [comment]
Hello Asher,
Yes, basically 1 - purity for normal. If the TIN-ratio is 0.1 (as default) and the normal is 30x coverage, any SV with the support < 3 reads in normal and detected in the tumor with enough support reads will be called somatic.

Best
Ayse

**Comment by apsteinberg** [comment]
Hi Ayse,

Okay great, thank you for explaining. Very much appreciate your help with this.

Best,
Asher

**Comment by eesiribloom** [comment]
if you only want to keep somatic variants with no support in normal reads, would you set `--TIN-ratio` to 0?
