### ISSUE TITLE
The number of somatic SVs is too less

### ISSUE THREAD

**Issue by DayTimeMouse** [KolmogorovLab/Severus#35]
Hi,

I used Severus to call somatic SVs, but the number of somatic SVs is only ~200(tumor/normal paired sample).Is it normal?

Best regards.

**Comment by aysegokce** [comment]
Hello,
We expect SVs around 100-2000 depending on the cancer type and stage. 200 is on the lower side but not unexpected; we observed cancer samples with < 50SVs. Some cancer types (subtypes) depend more on SNVs rather than SVs. 

Best
Ayse
