### ISSUE TITLE
severus for the tumor only mode

### ISSUE THREAD

**Issue by qinqian** [KolmogorovLab/Severus#7]
Dear authors, 

Thank you for developing such a great software. I am using severus to look at our own data, we only have tumor only sample, but in your pipeline, you mentioned the phased vcf should always come from the normal sample, could we use the tumor sample to generate input for the phased vcf? Also, could you please provide the command used in the following benchmarking section? Thank you!

<img width="752" alt="image" src="https://github.com/KolmogorovLab/Severus/assets/884386/85504e84-9b13-4b3f-ae23-33f9b8b69138">

Best wishes,
Alvin

**Comment by aysegokce** [comment]
Hello,
That is for somatic mode. In tumor-only mode, you can use phased vcf from the tumor. 
For the benchmarking, we used Minda (https://github.com/KolmogorovLab/minda), which will be available soon.

**Comment by qinqian** [comment]
Hello @aysegokce, 
Thank you so much for your quick reply! This clears our confusion, looking forward to Minda release soon. 
Best,
Alvin

**Comment by aysegokce** [comment]
Hello @qinqian ,
Germline mode is when there is no control sample (tumor-only, normal-only), and somatic is for a tumor/normal pair.  

In the somatic run, Severus outputs both somatic and germline SVs, and `--only-somatic` is to output only somatic SVs, which is more useful in large multi-sample studies. 

For tumor only runs:
```
 severus --target-bam phased_tumor.bam --out-dir severus_out -t 16 --phasing-vcf phased_tumor.vcf
--vntr-bed ./vntrs/human_GRCh38_no_alt_analysis_set.trf.bed
```
For somatic:
```
severus --target-bam phased_tumor.bam --control-bam phased_normal.bam --out-dir severus_out
-t 16 --phasing-vcf phased_normal.vcf --vntr-bed ./vntrs/human_GRCh38_no_alt_analysis_set.trf.bed
```
Sorry for the confusion. 
Ayse

**Comment by qinqian** [comment]
Thanks @aysegokce a lot for your explanation! Never mind, I learned a lot from your messages. 

Another question is about the difference between the two benchmarking sections [section 2](https://github.com/KolmogorovLab/Severus?tab=readme-ov-file#somatic-benchmarking-results-colo829) and [section 3](https://github.com/KolmogorovLab/Severus?tab=readme-ov-file#somatic-benchmarking-results-tumornormal-cell-line-pairs), is the section 2 showing the tumor-only mode? How to define somatic mutation when there is only tumor sample? Are you using gnomad af filtering?

**Comment by aysegokce** [comment]
In section 2, we used a multi-platform truth set to compare the performance of SV callers. In section 3, we sequenced cancer cell lines and their matching normals and generated an ensemble list for SV calls from four available somatic SV callers. In both sections, we have tumor and normal samples. 
We have single sample calls in [section 1](https://github.com/KolmogorovLab/Severus?tab=readme-ov-file#germline-benchmarking-results-using-hg002). In the tumor-only mode, we don't define somatic mutations.  We output complex events which are likely to be somatic. 
Ayse

**Comment by qinqian** [comment]
Thanks Ayse a lot! It looks crystal clear now.

**Comment by qinqian** [comment]
Hi Ayse,
I tried tumor-only mode with severus (version 0.1.1) with tumor sample phasing vcf, but there is zero SV in the somatic_SVs/*vcf, but there are plenty of SVs in the all_SVs/*.vcf, is this normal? Thanks!
Best,
Alvin

**Comment by aysegokce** [comment]
Hello Alvin,
Yes, we often get around 20k SVs (germline + somatic). In tumor-only cases, since there are no normal, Severus only outputs all_SVs. Depending on tumor purity, subclonal events (<0.4 vaf or <0.8 hVAF) are more likely to be somatic, whereas homozygous events (GT 1/1) are likely to be germline (if the coverage is preserved in the region). 
Ayse

**Comment by qinqian** [comment]
Hi Ayse,
Thank you so much for your explanation! 
Best,
Alvin
